src/AppBundle/Entity/ContractArtist.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Reward;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * ContractArtist
 *
 * @ORM\Table(name="contract_artist")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ContractArtistRepository")
 */
class ContractArtist extends BaseContractArtist
{
    const NB_DAYS_OF_CLOSING = 0;
    const FESTIVAL_START_HOUR = 18;
    const FESTIVAL_START_MINUTE = 0;

    const MAXIMUM_PROMO_OVERFLOW = 5;

    const STATE_REFUNDED = 'state.refunded';
    const STATE_FAILED = 'state.failed';
    const STATE_SUCCESS_SOLDOUT = 'state.success.soldout.soldout';
    const STATE_SUCCESS_SOLDOUT_PENDING = 'state.success.soldout.pending';
    const STATE_SUCCESS_CLOSED = 'state.success.closed';
    const STATE_SUCCESS_ONGOING = 'state.success.ongoing';
    const STATE_SUCCESS_PENDING = 'state.success.pending';
    const STATE_SUCCESS_PASSED = 'state.success.passed';
    const STATE_ONGOING = 'state.ongoing';
    const STATE_PENDING = 'state.pending';
    const STATE_TEST_PERIOD = 'state.test_period';

    public function __construct()
    {
        parent::__construct();
        $this->tickets_sold = 0;
        $this->tickets_reserved = 0;
        $this->tickets_sent = false;
        $this->nb_closing_days = self::NB_DAYS_OF_CLOSING;
        $this->min_tickets = 0;
        $this->festivaldays = new ArrayCollection();
        $this->known_lineup = false;
    }

    public function isUncrowdable() {
        return in_array($this->getState(), $this->getUncrowdableStates());
    }

    public function isSoldOut() {
        return in_array($this->getState(), $this->getSoldOutStates());
    }

    public function isCrowdable() {
        return !$this->isUncrowdable();
    }

    public function isPending() {
        return in_array($this->getState(), $this->getPendingStates());
    }

    public function getDisplayName() {
        if($this->artist == null) {
            $str = $this->step;
            foreach($this->getAllArtists() as $artist) {
                $str .= ' - ' . $artist;
            }
            return $str;
        }
        else {
            return $this->step . ' de ' . $this->artist;
        }
    }

    public function getFilterableFestivalDays() {
        if(!$this->successful && !$this->failed) {
            return $this->getFestivalDays();
        }
        return array_filter($this->getFestivaldays()->toArray(), function(FestivalDay $fd){
           return $fd->hasSuccessfulLineUps();
        });
    }

    public function getDisplayDates() {
        $str = '';
        $i = 1;
        foreach($this->getFestivalDates() as $date) {
            if($i > 1)
                $str .= ' - ';
            $str .= $date->format('d/m/Y');
            $i++;
        }
        return $str;
    }

    public function getTitleWithDates() {
        $str = $this->getTitle();
        if(!empty($this->getFestivalDates())) {
            $str .= ' (';
            $i = 1;
            foreach($this->getFestivalDates() as $date) {
                if($i > 1)
                    $str .= ' - ';
                $str .= $date->format('d/m');
                $i++;
            }
            $str.= ')';
        }
        return $str;
    }

    public static function getUncrowdableStates() {
        return [
            self::STATE_REFUNDED,
            self::STATE_FAILED,
            self::STATE_SUCCESS_SOLDOUT,
            self::STATE_SUCCESS_SOLDOUT_PENDING,
            self::STATE_SUCCESS_CLOSED,
            self::STATE_SUCCESS_PASSED,
            self::STATE_PENDING,
        ];
    }

    public static function getPendingStates() {
        return [
            self::STATE_PENDING,
            self::STATE_SUCCESS_PENDING,
            self::STATE_SUCCESS_SOLDOUT_PENDING,
        ];
    }

    public static function getSuccessfulStates() {
        return [
            self::STATE_SUCCESS_PENDING,
            self::STATE_SUCCESS_SOLDOUT,
            self::STATE_SUCCESS_SOLDOUT_PENDING,
            self::STATE_SUCCESS_CLOSED,
            self::STATE_SUCCESS_PASSED,
            self::STATE_SUCCESS_ONGOING,
        ];
    }

    public static function getPassedStates() {
        return [
            self::STATE_SUCCESS_PASSED,
            self::STATE_FAILED,
            self::STATE_REFUNDED,
        ];
    }

    public static function getSoldOutStates() {
        return [
            self::STATE_SUCCESS_SOLDOUT,
            self::STATE_SUCCESS_SOLDOUT_PENDING,
        ];
    }

    public function isInSuccessfulState() {
        return in_array($this->getState(), self::getSuccessfulStates());
    }

    public function isPassed() {
        return in_array($this->getState(), self::getPassedStates());
    }

    public function getTotalBookedTickets() {
        return $this->tickets_reserved + $this->getCounterpartsSold();
    }

    public function getTotalBookedTicketsRaw() {
        return $this->tickets_reserved + $this->getNbCounterPartsPaid();
    }

    public function getTotalBookedTicketsMajored() {
        return min($this->getTotalBookedTickets(), $this->getMaxTickets());
    }

    public function getLastSellingDate() {
        $dateconcert_copy = clone $this->getLastFestivalDate();
        return $dateconcert_copy->modify('-' . ($this->nb_closing_days) . ' days');
    }

    public function isLastSellingDate() {
        return (new \DateTime())->diff($this->getLastSellingDate())->days == 0 && (new \DateTime() >= $this->getLastSellingDate());
    }

    public function isDeadlineDate() {
        $today = new \DateTime();
        $di = $today->diff($this->dateEnd);
        // Careful, dateinterval:days works as it is the absolute number of days difference between today & deadline
        // dateinterval:d wouldn't work as it returns the difference between the days numeric values (e.g. 4 d diff between 11 may and 15 september)
        return $di->days == 0 && $di->h <= 24 && $today < $this->dateEnd;
    }


    public function getCampaignDaysLeft() {
        $today = new \DateTime();
        $di = $today->diff($this->dateEnd);
        return $di->days + 1; // + 1 because validation date usually is at midnight
    }

    /** @deprecated  */
    public function getTicketsSold() {
        return $this->getCounterpartsSold();
    }

    public function getTicketsSoldMajored() {
        return min($this->getCounterPartsSold(), $this->getMaxTickets());
    }

    public function getMaxTickets() {
        if(!empty($this->getFestivaldays())) {
            $normal_soldout = array_sum(array_map(function(FestivalDay $festivalDay) {
                return $festivalDay->getMaxTickets();
            }, $this->festivaldays->toArray()));
        }
        else {
            $normal_soldout = array_sum(array_map(function(CounterPart $counterPart) {
                return $counterPart->getMaximumAmount();
            }, $this->getCounterParts()->toArray()));
        }
        $global_soldout = $this->global_soldout == null ? $normal_soldout : $this->global_soldout;
        return min($global_soldout, $normal_soldout);
    }

    public function getTotalNbAvailable() {
        return $this->getMaxTickets() - $this->getTotalBookedTickets();
    }

    public function isValidatedBelowObjective() {
        return $this->isInSuccessfulState() && $this->getTicketsSold() < $this->getMinTickets();
    }

    public function getMinTickets() {
        if(!$this->hasNoThreshold() && $this->threshold <= 0 && $this->getStep() != null) {
            return $this->getStep()->getMinTickets();
        }
        else {
            return $this->threshold;
        }
    }

    public function getNbTicketsToSuccess() {
        $min = $this->getMinTickets();
        $booked = $this->getTotalBookedTickets();
        if($booked >= $min)
            return 0;

        return $min - $booked;
    }

    public function getState() {

        if(isset($this->state)) {
            return $this->state;
        }

        $today = new \DateTime();
        $today2 = new \DateTime();
        $today3 = new \DateTime();

        //$max_tickets = $this->getMaxTickets();

        // Failure & refunded
        if($this->refunded)
            return self::STATE_REFUNDED;

        // Marked as failure
        if($this->failed)
            return self::STATE_FAILED;

        // Or in pre-validaton
        if($this->isInTestPeriod()) {
            return self::STATE_TEST_PERIOD;
        }
        // Marked as success
        //if($this->successful)
        //{
            // Concert in the future
            if($this->getLastFestivalDate() >= $today3->modify('-1 day')) {
                // Sold out
          //      if ($this->getTotalBookedTickets() >= $max_tickets)
            //        return self::STATE_SUCCESS_SOLDOUT;
                // No more selling
          //      $dateConcert2 = clone $this->getLastFestivalDate();
            //    if ($today2->modify('+' . ($this->nb_closing_days) . ' days') > $dateConcert2)
              //      return self::STATE_SUCCESS_CLOSED;
                // Successful, in the future, not sold out, not closed => ongoing

                    return self::STATE_ONGOING;
            }
            else {
            return self::STATE_SUCCESS_PASSED;
            }
            // Concert in the passed & successful
            //else
            //    return self::STATE_SUCCESS_PASSED;
        //}

        /* Crowdfunding is not over yet
        if($this->dateEnd > (new \DateTime())) {
            // But already sold out
            if ($this->getTotalBookedTickets() >= $max_tickets)
                return self::STATE_SUCCESS_SOLDOUT_PENDING;

            // Or already successful but not sold out and with a need of validation
            if ($this->getTotalBookedTickets() >= $this->getMinTickets())
                return self::STATE_SUCCESS_PENDING;

src/AppBundle/Form/ContractArtistType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Artist;
use AppBundle\Entity\BaseContractArtist;
use AppBundle\Entity\ContractArtist;
use AppBundle\Entity\Province;
use AppBundle\Entity\Step;
use AppBundle\Entity\StepType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\NotBlank;

class ContractArtistType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // TODO ROLE_ADMIN
        $user = $options['user']->hasRole('ROLE_SUPER_ADMIN') ? null : $options['user'];

        switch ($options['flow_step']) {
            case 1:
                $builder
                    ->add('artist', EntityType::class, array(
                        'label' => 'labels.contractartist.artist',
                        'class' => Artist::class,
                        'query_builder' => function (EntityRepository $er) use ($user) {
                            return $er->queryNotCurrentlyBusy($user);
                        },
                        'constraints' => [
                            new NotBlank(['message' => 'contractartist.artist.blank']),
                        ],
                    ))
                    ->add('province', EntityType::class, array(
                        'label' => 'labels.contractartist.province',
                        'required' => false,
                        'class' => Province::class,
                        'placeholder' => 'Sans importance', // TODO translate
                    ))
                    ->add('step', EntityType::class, array(
                        'label' => 'labels.contractartist.step',
                        'class' => Step::class,
                        'query_builder' => function(EntityRepository $er) {
                            return $er->createQueryBuilder('step')
                                ->orderBy('step.min_tickets', 'ASC');
                        },
                        'choice_label' => 'displayWithMinTickets',
                        'constraints' => [
                            new NotBlank(['message' => 'contractartist.artist.blank']),
                        ],
                    ));
                break;
            case 2:
                $builder
                    ->add('preferences', ConcertPossibilityType::class, array(
                        'label' => false,
                        'required' => true,
                        'available-dates' => $options['available-dates'],
                    ))
                    ->add('motivations', TextareaType::class, array(
                        'label' => 'labels.contractartist.motivations',
                        'required' => false,
                    ));
                break;
            case 3:
                if ($user == null) {
                    $builder
                        ->add('testPeriod', CheckboxType::class, array(
                            'required' => false,
                            'label' => 'Doit avoir une période de test',
                        ))
                        ->add('reality', ConcertPossibilityType::class, array(
                            'label' => 'Détails connus',
                            'required' => false,
                            'required_reality' => false,
                            'is_reality' => true,
                            'available-dates' => $options['available-dates'],
                            'date_value' => $builder->getData()->getPreferences()->getDate(),
                        ));
                }
                $builder->add('accept_conditions', CheckboxType::class, array(
                        'label' => 'labels.contractartist.accept_conditions',
                        'required' => true,
                        'constraints' => [
                            new IsTrue(['message' => 'contractartist.accept_conditions.blank']),
                        ],
                    ))
                ;
                break;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_contractartist';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'user' => null,
            'available-dates' => null,
            'data_class' => ContractArtist::class,
        ));
    }


}

src/AppBundle/Resources/views/Admin/ContractArtist/action_mails.html.twig
{% extends 'sonata_admin_layout.html.twig' %}

{% block sonata_admin_content %}

    <div class="content-box">
        <div class="content-box-content">
            <h2>Envoi des mails pour {{ contract }}</h2>

            <p><a href="{{ path('artist_contract', {'id':contract.id, 'slug': contract.slug}) }}">Voir la page de l'événement.</a></p>

            {% if not (contract.successful or contract.failed) %}
                <p>
                    Cet événement n'est pas marqué comme réussi ; impossible d'envoyer les mails !
                </p>
            {% else %}
                <p>
                    Cet événement est marqué comme réussi. Tu peux donc envoyer les mails qui confirmeront les commandes en fonction de la réussite des lineups.
                    <b>Attention : il faut absolument avoir marqué auparavant dans la base de données quelles line-ups sont réussies et lesquelles sont en échec.</b>
                </p>

                <div>
                    {{ form_errors(form) }}
                    {{ form_start(form) }}

                    <div class="form-group">
                        {{ form_widget(form.send) }}
                        {{ form_widget(form.cancel) }}
                    </div>

                    {% do form.preview.setRendered(true) %}
                    {{ form_rest(form) }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/ContractArtist/action_prevalidate.html.twig
{% extends 'sonata_admin_layout.html.twig' %}

{% block sonata_admin_content %}

    <div class="content-box">
        <div class="content-box-content">
            <h2>Mettre fin à la période de pré-validation de l'événement "{{ contract }}"</h2>

            <p>
                C'est le {{ contract.currentTestDayNb }}è jour de pré-validation de cet événement.
            <p>
            <ul>
                <li>
                    Si tu marques la pré-validation comme <strong>réussie</strong>, alors l'événement sera dévoilé au grand public sur la plateforme.
                    Les ventes officielles commenceront à partir d'aujourd'hui.
                </li>
                <li>
                    Si tu marques la pré-validation comme <strong>ratée</strong>, alors il ne sera plus possible d'acheter des tickets et l'événement sera considéré comme tout événement raté.
                    N'oublie pas dans ce cas d'également rembourser les gens qui ont acheté des tickets.
                </li>
            </ul>

            <div>
                {{ form_start(form) }}

                <div class="form-group">
                    {{ form_widget(form.marksuccessful) }}
                    {{ form_widget(form.markfailed) }}
                    {{ form_widget(form.cancel) }}
                </div>

                {{ form_rest(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/ContractArtist/action_refund.html.twig
{% extends 'sonata_admin_layout.html.twig' %}

{% block sonata_admin_content %}

    <div class="content-box">
        <div class="content-box-content">
            <h2>Demande de remboursement</h2>

            <p>
                Es-tu sûr de vouloir rembourser tous les participants à ce crowdfunding ? {% if contract.isOneStepFromBeingRefunded %}(cela le remboursera immédiatement){% else %}(il y aura besoin de la validation d'autres admins avant le remboursement){% endif %}
            </p>

            {% if not contract.failed %}
                <div class="alert alert-danger">Attention : le crowdfunding n'est pas un échec pour l'instant. Réfléchis bien avant de rembourser tous les participants !</div>
            {% endif %}

            <div>
                {{ form_start(form) }}

                <div class="form-group">
                    {{ form_widget(form.confirm) }}
                    {{ form_widget(form.cancel) }}
                </div>

                {{ form_rest(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/ContractArtist/action_refunds.html.twig
{% extends 'sonata_admin_layout.html.twig' %}

{% block sonata_admin_content %}

    <div class="content-box">
        <div class="content-box-content">
            <h2>Envoi des remboursements pour {{ contract }}</h2>

            <p><a href="{{ path('artist_contract', {'id':contract.id, 'slug': contract.slug}) }}">Voir la page de l'événement.</a></p>

            {% if not (contract.successful or contract.failed) %}
                <p>
                    Cet événement n'est pas marqué comme réussi ; impossible d'envoyer les mails !
                </p>
            {% else %}
                <p>
                    Cet événement est marqué comme réussi. Tu peux donc envoyer les remboursements des commandes dont les artistes sélectionnés font partie d'une line-up en échec.
                    <b>Attention : il faut absolument avoir auparavant envoyé les mails de confirmation.</b>
                </p>

                <div>
                    {{ form_errors(form) }}
                    {{ form_start(form) }}

                    <div class="form-group">
                        {{ form_widget(form.send) }}
                        {{ form_widget(form.cancel) }}
                    </div>

                    {% do form.preview.setRendered(true) %}
                    {{ form_rest(form) }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/ContractArtist/action_tickets.html.twig
{% extends 'sonata_admin_layout.html.twig' %}

{% block sonata_admin_content %}

    <div class="content-box">
        <div class="content-box-content">
            <h2>Envoi des tickets pour {{ contract }}</h2>

            <p><a href="{{ path('artist_contract', {'id':contract.id, 'slug': contract.slug}) }}">Voir la page de l'événement.</a></p>

            {% if not contract.successful %}
                <p>
                    Cet événement n'est pas marqué comme réussi ; impossible d'envoyer des tickets !
                </p>
            {% else %}
                <p>
                    Cet événement est marqué comme réussi. Tu peux donc expédier les tickets. Ils seront envoyés par mail.
                </p>

                <div>
                    {{ form_errors(form) }}
                    {{ form_start(form) }}

                    <div class="form-group">
                        {{ form_widget(form.send) }}
                        {{ form_widget(form.preview) }}
                        {{ form_widget(form.cancel) }}
                    </div>

                    {{ form_rest(form) }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/ContractArtist/action_validate.html.twig
{% extends 'sonata_admin_layout.html.twig' %}

{% block sonata_admin_content %}

    <div class="content-box">
        <div class="content-box-content">
            <h2>Validation de concert</h2>

            {% if contract.pending %}
                {% if contract.state is constant('STATE_PENDING', contract) %} {# Deadline hit #}
                    <p>
                        Cet événement est arrivé à échéance et attend ta décision pour être confirmé ou non.
                    </p>
                    <p>
                        À première vue, le contrat est {% if contract.ticketsSold >= contract.step.minTickets %}rempli !{% else %}un échec...{% endif %}.
                    </p>
                {% else %}
                    {# No deadline hit -> success before deadline #}
                    <p>
                        Cet événement a atteint le seuil de ventes requis ! Il n'y a plus qu'à le confirmer en renseignant la salle et la date confirmées.
                    </p>

                    <p>
                        S'il s'agit d'une erreur ou d'un test, tu as aussi la possibilité de marquer l'événement comme un échec.
                    </p>
                {% endif %}

                <p><a href="{{ path('artist_contract', {'id':contract.id, 'slug': contract.getSlug}) }}">Voir la page de l'événement.</a></p>

                <p class="alert alert-warning">
                    Attention, quelle que soit ta décision, un mail sera envoyé à tous les crowdfundeurs pour la leur annoncer.
                </p>

                <div>
                    {{ form_start(form) }}

                    <p>
                        ATTENTION : relis bien ces infos car elles seront envoyées par mail si tu confirmes le concert !
                        Si tu souhaites marquer le concert comme raté, laisse les valeurs par défaut.
                    </p>

                    <div class="form-group">
                        {{ form_widget(form.acceptConditions) }}
                    </div>

                    <div class="form-group">
                        {{ form_widget(form.marksuccessful) }}
                        {{ form_widget(form.markfailed) }}
                    </div>

                    {{ form_rest(form) }}
                </div>
            {% else %}
                Tu ne peux pas confirmer un concert tant que l'échéance de la vente de tickets n'a pas été atteinte.
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/ContractArtist/icon_mails.html.twig
{% if object.successful or object.failed %}
    <br /><a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('mails', object) }}">Envoyer les e-mails</a>
{% endif %}

src/AppBundle/Resources/views/Admin/ContractArtist/icon_payments.html.twig
<a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('payments', object) }}">Télécharger l'Excel des paiements</a>

src/AppBundle/Resources/views/Admin/ContractArtist/icon_prevalidate.html.twig
{% if object.isInTestPeriod %}
        <a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('prevalidate', object) }}">Mettre fin à la pré-validation ({{ object.currentTestDayNb }}è jour de test)</a>
{% endif %}

src/AppBundle/Resources/views/Admin/ContractArtist/icon_refund.html.twig
{% if not object.refunded %}
    {% if object.isAskedRefundBy(app.user) %}
        <a class="btn btn-sm btn-default disabled">Remboursement demandé</a>
    {% elseif not object.refunded %}
        <a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('refund', object) }}">Rembourser</a>
        {% if object.isAskedRefundByOne %}
            {% set askings = object.askingrefund %}
            (remboursement proposé par {% for asking in askings %}{{ asking.displayName}} {% endfor %})
        {% endif %}
    {% endif %}
{% endif %}

src/AppBundle/Resources/views/Admin/ContractArtist/icon_refunds.html.twig
{% if object.successful or object.failed %}
    <br /><a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('refunds', object) }}">Lancer les remboursements</a>
{% endif %}

src/AppBundle/Resources/views/Admin/ContractArtist/icon_tickets.html.twig
{% if object.successful %}
    <a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('tickets', object) }}">Envoyer les tickets</a>
{% endif %}

src/AppBundle/Resources/views/Admin/ContractArtist/icon_validate.html.twig
{% if object.pending %}
    <a class="btn btn-sm btn-default" href="{{ admin.generateObjectUrl('validate', object) }}">Conclure</a>
{% endif %}