src/AppBundle/Entity/Artist.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Sonata\TranslationBundle\Model\TranslatableInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ArtistRepository")
 * @ORM\Table(name="artist")
 **/
 // @UniqueEntity("artistname", repositoryMethod="findNotDeleted")
class Artist implements TranslatableInterface
{
    use ORMBehaviors\Translatable\Translatable;
    use ORMBehaviors\Sluggable\Sluggable;

    const PHOTOS_DIR = 'uploads/artist_gallery/';

    public static function getWebPath(Photo $photo) {
        return self::PHOTOS_DIR . $photo->getFilename();
    }

    public function __call($method, $arguments)
    {
        try {
            return $this->proxyCurrentLocaleTranslation($method, $arguments);
        } catch(\Exception $e) {
            $method = 'get' . ucfirst($method);
            return $this->proxyCurrentLocaleTranslation($method, $arguments);
        }
    }

    public function getDefaultLocale() {
        return 'fr';
    }

    public function __toString()
    {
        return '' . $this->artistname;
    }

    public function __construct(Phase $phase = null)
    {
        $this->phase = $phase;
        $this->deleted = false;
        $this->genres = new ArrayCollection();
        $this->artists_user = new ArrayCollection();
        $this->ownership_requests = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->date_creation = new \DateTime();
        $this->accept_conditions = false;
        $this->visible = false;
        $this->validated = false;
        $this->information_session = null;
    }

    public function getSluggableFields() {
        return ['artistname'];
    }

    public function setLocale($locale)
    {
        $this->setCurrentLocale($locale);
        return $this;
    }

    public function getLocale()
    {
        return $this->getCurrentLocale();
    }

    public function getSafename() {
        return $this->slug;
    }

    public function isActive() {
        return !$this->deleted;
    }

    public function getOwners() {
        return array_map(function($elem) {
                return $elem->getUser();
        }, $this->artists_user->toArray());
    }

    public function getScore(User $user) {
        if(mt_rand(1,2) == 1) { return 0; }

        $score = 0;
        foreach($user->getGenres() as $genre) {
            if($this->genres->contains($genre)) {
                if(mt_rand(1,3) > 1) {
                   $score++;
                }
            }
        }
        return $score;
    }

    public function canBeLeft() {
        $currentContract = $this->currentContract();
        return $currentContract == null;
    }

    public function isAvailable() {
        $currentContract = $this->currentContract(true);
        return $currentContract == null || $currentContract->isInSuccessfulState();
    }

    public function hasCurrentContract() {
        return $this->currentContract() != null;
    }

    public function hasOneLink() {
        return !empty($this->website)
            || !empty($this->twitter)
            || !empty($this->facebook)
            || !empty($this->spotify)
            || !empty($this->soundcloud)
            || !empty($this->bandcamp)
            || !empty($this->instagram)
        ;
    }

    public function getAllPhotos() {
        $photos = array();

        if($this->profilepic != null) {
            $photos[] = $this->profilepic;
        }
        foreach($this->photos as $p) {
            $photos[] = $p;
        }

        return $photos;
    }

    // Unmapped
    private $currentContracts = false;

    public function currentContract($allow_preval = false) {
        if($this->currentContracts === false) {
            $this->currentContracts = [];

            foreach($this->getPerformances() as $performance) {
                $festivalDay = $performance->getFestivalDay();
                $contract = $festivalDay->getFestival();
                if($festivalDay->getDate()  >= (new \DateTime()) && !$contract->getFailed()) {
                    $this->currentContracts[] = $contract;
                }
            }
            $this->currentContracts = array_unique($this->currentContracts);
        }
        return $this->currentContracts;
    }

    public function currentContracts() {
        return $this->currentContract();
    }

    public function getPassedSuccessfulContracts() {
        $contracts = [];

        foreach($this->contracts as $contract) {
            /** @var ContractArtist $contract */
            if($contract->getLastFestivalDate() < (new \DateTime()) && $contract->getSuccessful() && !$contract->getFailed()) {
                $contracts[] = $contract;
            }
        }

        return $contracts;
    }

    public function getInformationSessionWithDate() {
        if($this->information_session)
            return $this->information_session->getNameWithDate();
        return '';
    }

    // Form only

    private $accept_conditions;
    public function getAcceptConditions() {return $this->accept_conditions;}
    public function setAcceptConditions($ac) { $this->accept_conditions = $ac; return $this;}

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="artistname", type="string", length=67)
     */
    private $artistname;

    /**
     * @ORM\ManyToOne(targetEntity="Phase")
     * @ORM\JoinColumn(nullable=true)
     */
    private $phase;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Genre")
     */
    private $genres;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="Artist_User", mappedBy="artist")
     */
    private $artists_user;

    /**
     * @var Province
     * @ORM\ManyToOne(targetEntity="Province")
     */
    private $province;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="ArtistOwnershipRequest", mappedBy="artist", cascade={"persist"})
     */
    private $ownership_requests;

    /**
     * @ORM\Column(name="deleted", type="boolean")
     */
    private $deleted;

    /**
     * @var Photo
     *
     * @ORM\OneToOne(targetEntity="Photo", cascade={"all"})
     */
    private $profilepic;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Photo", cascade={"all"})
     */
    private $photos;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Video", cascade={"all"})
     */
    private $videos;

    /**
     * @var string
     * @ORM\Column(name="website", type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @var string
     * @ORM\Column(name="facebook", type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @var string
     * @ORM\Column(name="twitter", type="string", length=255, nullable=true)
     */
    private $twitter;

    /**
     * @var string
     * @ORM\Column(name="spotify", type="string", length=255, nullable=true)
     */
    private $spotify;

    /**
     * @var string
     * @ORM\Column(name="soundcloud", type="string", length=255, nullable=true)
     */
    private $soundcloud;

    /**
     * @var string
     * @ORM\Column(name="bandcamp", type="string", length=255, nullable=true)
     */
    private $bandcamp;

    /**
     * @var string
     * @ORM\Column(name="instagram", type="string", length=255, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(name="date_creation", type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity="BaseContractArtist", mappedBy="artist")
     */
    private $base_contracts;

    /**
     * @ORM\OneToMany(targetEntity="ContractArtist", mappedBy="main_artist")
     */
    private $contracts;

    /**
     * @var bool
     * @ORM\Column(name="visible", type="boolean")
     */
    private $visible;

    /**
     * @var bool
     * @ORM\Column(name="validated", type="boolean")
     */
    private $validated;

    /**
     * @ORM\Column(name="phone", type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity="ArtistPerformance", mappedBy="artist")
     */
    private $performances;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\InformationSession", inversedBy="artists")
     * @ORM\JoinColumn(nullable=true)
     */
    private $information_session;

    // Form only
    /** @var ArrayCollection */
    public $ownership_requests_form;

    /**
     * Set artistname
     *
     * @param string $artistname
     *
     * @return Artist
     */
    public function setArtistname($artistname)
    {
        $this->artistname = $artistname;

        return $this;
    }

    /**
     * Get artistname
     *
     * @return string
     */
    public function getArtistname()
    {
        return $this->artistname;
    }

    /**
     * Set phase
     *
     * @param \AppBundle\Entity\Phase $phase
     *
     * @return Artist
     */
    public function setPhase(\AppBundle\Entity\Phase $phase)
    {
        $this->phase = $phase;

        return $this;
    }

    /**
     * Get phase
     *
     * @return \AppBundle\Entity\Phase
     */
    public function getPhase()
    {
        return $this->phase;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Add genre
     *
     * @param \AppBundle\Entity\Genre $genre
     *
     * @return Artist
     */
    public function addGenre(\AppBundle\Entity\Genre $genre)
    {
        $this->genres[] = $genre;

        return $this;
    }

    /**
     * Remove genre
     *

src/AppBundle/Entity/LineUp.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Sonata\TranslationBundle\Model\TranslatableInterface;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\LineUpRepository")
 * @ORM\Table(name="lineup")
 **/
class LineUp implements TranslatableInterface
{
    use ORMBehaviors\Translatable\Translatable;

    public function __construct()
    {
        $this->performances = new ArrayCollection();
        $this->ticketsSold = 0;
        $this->ticketsSoldPostVal = 0;
        $this->successful = 0;
        $this->failed = 0;
    }

    public function __call($method, $arguments)
    {
        try {
            return $this->proxyCurrentLocaleTranslation($method, $arguments);
        } catch(\Exception $e) {
            $method = 'get' . ucfirst($method);
            return $this->proxyCurrentLocaleTranslation($method, $arguments);
        }
    }

    public function getDefaultLocale() {
        return 'fr';
    }

    public function __toString()
    {
        if($this->festivalDay == null || $this->stage == null) {
            return 'Nouvelle lineup';
        }
        return $this->getFestivalDay()->__toString() . ' (lineup ' .  $this->getName() . ' @'.$this->stage->__toString();
    }

    public function setLocale($locale)
    {
        $this->setCurrentLocale($locale);
        return $this;
    }

    public function getLocale()
    {
        return $this->getCurrentLocale();
    }

    public static function sortPerformancesAsc($performances) {
        if( count( $performances) < 2 ) {
            return $performances;
        }
        $left = $right = array( );
        reset( $performances);

        $pivot_key  = key( $performances );
        $pivot  = array_shift( $performances );

        foreach( $performances as $k => $v ) {
            if($pivot->getTime() == null || $v->getTime() < $pivot->getTime() )
                $left[$k] = $v;
            else
                $right[$k] = $v;
        }
        return array_merge(self::sortPerformancesAsc($left), array($pivot_key => $pivot), self::sortPerformancesAsc($right));
    }


    public function getPerformancesAsc() {
        $performances = $this->performances->toArray();
        return self::sortPerformancesAsc($performances);
    }

    public function getFestival() {
        if($this->festivalDay == null) {
            return null;
        }
        return $this->festivalDay->getFestival();
    }

    public function getArtistPerformances() {
        return $this->getPerformances();
    }

    public function getArtists() {
        return array_map(function (ArtistPerformance $ap) {
            return $ap->getArtist();
        }, $this->performances->toArray());
    }

    public function addTicketsSold($quantity) {
        $this->ticketsSold += $quantity;
    }
    public function addTicketsSoldPostVal($quantity) {
        $this->ticketsSoldPostVal += $quantity;
    }

    public function getPercentageObjective() {
        if($this->threshold == 0) {
            return 0;
        }
        return round(($this->ticketsSold / $this->threshold) * 100, 0);
    }

    public function isSoldOut() {
        return $this->soldout_amount <= $this->ticketsSold;
    }

    public function getNbAvailable() {
        return $this->soldout_amount - $this->ticketsSold;
    }

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="FestivalDay", inversedBy="lineups")
     * @var FestivalDay
     */
    protected $festivalDay;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\ArtistPerformance", mappedBy="lineup")
     */
    private $performances;

    /**
     * @var Stage
     * @ORM\ManyToOne(targetEntity="Stage", inversedBy="lineups")
     * @ORM\JoinColumn(nullable=true)
     */
    private $stage;

    /**
     * @ORM\Column(name="tickets_sold", type="float")
     */
    private $ticketsSold;

    /**
     * @ORM\Column(name="tickets_sold_post_val", type="float")
     */
    private $ticketsSoldPostVal;

    /**
     * @ORM\Column(name="threshold", type="float")
     */
    private $threshold;

    /**
     * @ORM\Column(name="soldout_amount", type="float")
     */
    private $soldout_amount;

    /**
     * @ORM\Column(name="successful", type="boolean")
     */
    private $successful;

    /**
     * @ORM\Column(name="failed", type="boolean")
     */
    private $failed;

    /**
     * Add performance
     *
     * @param \AppBundle\Entity\ArtistPerformance $performance
     *
     * @return LineUp
     */
    public function addPerformance(\AppBundle\Entity\ArtistPerformance $performance)
    {
        $this->performances[] = $performance;

        return $this;
    }

    /**
     * Remove performance
     *
     * @param \AppBundle\Entity\ArtistPerformance $performance
     */
    public function removePerformance(\AppBundle\Entity\ArtistPerformance $performance)
    {
        $this->performances->removeElement($performance);
    }

    /**
     * Get performances
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPerformances()
    {
        return $this->performances;
    }

    public function getFestivalDay() {
        return $this->festivalDay;
    }
    public function setFestivalDay($festivalDay) {
        $this->festivalDay = $festivalDay;
        return $this;
    }
    public function getStage() {
        return $this->stage;
    }
    public function setStage($stage) {
        $this->stage = $stage;
        return $this;
    }
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function setTicketsSold($quantity) {
        $this->ticketsSold = $quantity;
        return $this;
    }
    public function getTicketsSold() {
        return $this->ticketsSold;
    }

    public function setThreshold($threshold) {
        $this->threshold = $threshold;
        return $this;
    }
    public function getThreshold() {
        return $this->threshold;
    }
    public function setSoldoutAmount($soldout_amount) {
        $this->soldout_amount = $soldout_amount;
        return $this;
    }
    public function getSoldoutAmount() {
        return $this->soldout_amount;
    }

    public function setSuccessful($successful) {
        $this->successful = $successful;
        return $this;
    }
    public function getSuccessful() {
        return $this->successful;
    }
    public function isSuccessful() {
        return $this->getSuccessful();
    }
    public function setFailed($failed) {
        $this->failed = $failed;
        return $this;
    }
    public function getFailed() {
        return $this->failed;
    }
    public function isFailed() {
        return $this->getFailed();
    }

    /**
     * @return mixed
     */
    public function getTicketsSoldPostVal()
    {
        return $this->ticketsSoldPostVal;
    }

    /**
     * @param mixed $ticketsSoldPostVal
     */
    public function setTicketsSoldPostVal($ticketsSoldPostVal)
    {
        $this->ticketsSoldPostVal = $ticketsSoldPostVal;
        return $this;
    }
}

src/AppBundle/Resources/views/Public/Card/artist.html.twig
{% extends ":patterns:card.html.twig" %}

{% block card_content %}

    {% set rotation = false %}
    {% set src = asset('images/artist-card-default.jpg') %}

    {% set photos = artist.allPhotos %}

    {% if photos is not empty %}
        {% for photo in photos %}
            {% if loop.first %}
                {% set src = absolute_url(asset(artist.webPath(photo))) %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {#<a class="um-card-link" href="{{ path('artist_profile', {'id': artist.id, 'slug': artist.slug}) }}">
    <div style="position: relative; left: 0; top: 0;">
            <div style="position: relative; top: 0; left: 0;">
                <img src="{{ src }}" width="300px" height="200px"/>
            </div>
            {% if hours is defined and hours is not null %}
                <span class="card-caption-2 position-absolute">{{ hours }}</span>
            {% endif %}
            <div style="background-color: black; position:absolute; bottom: 0; right: 0; padding-left: 15px; padding-right: 15px; padding-top: 10px; border-radius: 10px 0 0 0">
                <p style="color: #E79A41"><span class="artist-name">{{ artist.artistname }}</span></p>
            </div>
        </div>
        <div style="width: 300px">
            <div>
                <span class="d-none artist-genres">{% for genre in artist.genres %}{% if not loop.first %} {% endif %}<span class="jplist-{{ genre|slug }}">{{ genre }}</span>{% endfor %}</span>
                {% if artist.hasCurrentContract %}<span class="d-none artist-has-current-contract"></span>{% endif %}
            </div>
        </div>
    </a>#}
    <a class="um-card-link" href="{{ path('artist_profile', {'id': artist.id, 'slug': artist.slug}) }}">
    <div class="bg-white">
        <div class="mx-auto w-100 position-relative">
            <div class="w-100 defaultHeightBg ratio-23 artist-card" style="background-image: url({{ src }});"></div>
            {% if hours is defined and hours is not null %}
                <span class="card-caption-2 position-absolute">{{ hours }}</span>
            {% endif %}
            <span class="card-caption position-absolute artist-name">{{ artist.artistname }}</span>
        </div>

        <!-- this is the content of the card with an optionnal span for ⭐ -->
        <div>
            <span class="d-none artist-genres">{% for genre in artist.genres %}{% if not loop.first %} {% endif %}<span class="jplist-{{ genre|slug }}">{{ genre }}</span>{% endfor %}</span>
            {% if artist.hasCurrentContract and not artist.currentContract[0].isCancelledArtist(artist) %}<span class="d-none artist-has-current-contract"></span>{% endif %}
        </div>

        <!-- this is the link that the card need to take to -->

    </div>
    </a>
{% endblock %}

src/AppBundle/Resources/views/Public/Card/contract_artist.html.twig
{% extends ':patterns:card.html.twig' %}

{% block card_content %}

    {% set rotation = false %}
    {% set progress_100 = contract.percentObjective %}
    {% set state = contract.state %}

    {% set is_event = contract is instanceof('\\AppBundle\\Entity\\ContractArtist') %}
    {% set is_pot = contract is instanceof('\\AppBundle\\Entity\\ContractArtistPot') %}
    {% set is_sales = contract is instanceof('\\AppBundle\\Entity\\ContractArtistSales') %}

    {% set src = is_sales and contract.artist is not null and contract.artist.profilepic is not null ? contract.artist.webPath(contract.artist.profilepic) :
        (contract.photo is not null ? contract.webPath(contract.photo) : 'images/live/live-6.jpg') %}

    {% set url_contract = is_event ? path('artist_contract', {'id': contract.id, 'slug': contract.slug}) :
        (is_pot ? path('pot_pot', {'id': contract.id, 'slug': contract.artist.slug}) : path('artist_contract_sales', {'id': contract.id, 'slug': contract.artist.slug})) %}

        <div class="thumbnail img-thumb-bg{% for class in card_classes %} {{ class }}{% endfor %}" style="background-image: url('{{ asset(src) }}');">
            {% if clickable %}
                <a class="thumbnail-link" href="{{ url_contract }}"></a>
            {% endif %}
            <div class="w-100 position-absolute" style="z-index:1000;">
                <div class="progress">
                    <div class="progress-bar{% if state in contract.successfulStates %} successful-progress-bg{% endif %}"
                         style="padding-left: 1rem;width:{{ progress_100 }}%"></div>
                </div>
                <div class="pt-2 pr-2 text-right small font-weight-bold text-uppercase{% if state in contract.successfulStates %} text-black{% else %} text-primary{% endif %}">
                    {{ progress_100 }}% des tickets nécessaires à la validation de l'événement<br/>{{ ('event.'~state)|trans({'%soldout_percentage%':contract.percentSoldOutRelativeToObjective})|raw }}
                </div>
            </div>
            <div class="overlay"></div>

            <div class="caption mt-4 pt-5">
                <h5 class="title"><a href="{{ url_contract }}">{{ contract.getTitle }}</a></h5>
                <div class="clearfix">
                    {% if is_event %}
                        {% if contract.festivalDates is not empty %}
                            <div><i class="fas fa-calendar-alt"></i> {{ contract.displayDates }}</div>
                        {% endif %}
                        {% if contract.festivalHalls is not empty %}
                            <div><i class="fas fa-map-marker-alt"></i> {{ contract.displayHalls }}</div>
                        {% endif %}
                    {% endif %}
                    <div class="artists-list">
                        {% for art in contract.allArtists %}{% if not loop.first %} - {% endif %}{{ art }}{% endfor %}</div>
                    </div>

                {% if is_event %}
                    {% set progress_100 = contract.percentObjective %}
                    <span class="d-none event-gauge">{{ contract.isInSuccessfulState ? 100 : progress_100 }}</span>
                    <span class="d-none event-date">{% if contract.festivalDates is not empty %}{{ contract.festivalDates[0]|date('m/d/Y') }}{% endif %}</span>
                    <span class="d-none event-genres">{% for genre in contract.genres %}<span class="d-none jplist-{{ genre|slug }}">{% if not loop.first %} {% endif %}{{ genre }}</span>{% endfor %}</span>
                    <span class="d-none event-state {% if contract.isInSuccessfulState %}event-confirmed{% else %}event-not-confirmed{% endif %}{% if contract.soldOut %} event-sold-out{% endif %}">{{ contract.state }}</span>
                {% else %}

                {% endif %}
            </div>
        </div>

{% endblock %}

src/AppBundle/Resources/views/Public/Card/hall.html.twig
{% extends ':patterns:card.html.twig' %}

{% block card_content %}

    {% set rotation = false %}
    {% set src = asset('images/hall-card-default.jpg') %}

    {% if hall.photos is not empty %}
        {% set rotation = true %}
        {% set imgstring = '[' %}
        {% for photo in hall.photos %}
            {% if loop.first %}
                {% set src = absolute_url(asset(hall.webPath(photo))) %}
            {% endif %}
            {% set imgstring = imgstring ~ '"' ~ absolute_url(asset(hall.webPath(photo))) ~ '"' %}
            {% if not loop.last %}
                {% set imgstring = imgstring ~ "," %}
            {% else %}
                {% set imgstring = imgstring ~ ']' %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if no_rotation_hall is defined and no_rotation_hall %}
        {% set rotation = false %}
    {% endif %}

    <div class="bg-white" >
        <div class="mx-auto w-75 position-relative">
            <div class="defaultHeightBg sepia ratio-23" style="background-image: url({{ src }});"></div>
            <span class="card-caption position-absolute">{{ hall.name }}</span>
        </div>

        <!-- this is the content of the card with an optionnal span for ⭐ -->
        <div class="mt-2">
            <div class="font-weight-light text-center">{{ hall.address }}</div>
            {#<p>{{ preview(hall.getShortDescription(), 100)|raw }}</p>#}
            {% if hall.website is not empty %}
                <div class="text-right my-1">
                    <a class="btn btn-primary" target="_blank" href="{{ absolute_url(hall.website) }}">{{ 'more_info'|trans }}</a>
                </div>
            {% endif %}
        </div>


    </div>
{% endblock %}