src/XBundle/Entity/Project.php
<?php

namespace XBundle\Entity;

use AppBundle\Entity\Address;
use AppBundle\Entity\Artist;
use AppBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use XBundle\Entity\Image;
use XBundle\Entity\Product;
use XBundle\Entity\Tag;
use XBundle\Entity\XContractFan;
use XBundle\Entity\XCategory;

/**
 * Project
 *
 * @ORM\Table(name="project")
 * @ORM\Entity(repositoryClass="XBundle\Repository\ProjectRepository")
 */
class Project
{
    use ORMBehaviors\Sluggable\Sluggable;
    use ORMBehaviors\SoftDeletable\SoftDeletable;

    const DAYS_BEFORE_WAY_PASSED_EVENT = 15;
    const DAYS_BEFORE_WAY_PASSED = 30;

    const PHOTOS_DIR = 'x/images/projects/';

    public function __construct() {
        $this->dateCreation = new \DateTime();
        $this->dateEnd = new \DateTime();
        $this->collectedAmount = 0;
        $this->validated= false;
        $this->successful = false;
        $this->failed = false;
        $this->refunded = false;
        $this->noThreshold = true;
        $this->code = uniqid('x');
        $this->projectPhotos = new ArrayCollection();
        $this->handlers = new ArrayCollection();
        $this->products = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->acceptConditions = false;
        $this->contributions= new ArrayCollection();
        $this->notifEndSent = 0;
        $this->notifSuccessSent = 0;
        $this->transactionalMessages = new ArrayCollection();
    }

    public function getSluggableFields() {
        return ['title'];
    }

    public static function getWebPath(Image $image) {
        return self::PHOTOS_DIR . $image->getFilename();
    }

    public function __toString()
    {
        return '' . $this->getTitle();
    }

    /**
     * Check if project has threshold
     * @return bool
     */
    public function hasThreshold()
    {
        return !$this->noThreshold;
    }

    /**
     * Check if project has validated products
     * @return bool
     */
    public function hasValidatedProducts() {
        $validatedProducts = array_filter($this->getProducts()->toArray(), function(Product $product) {
                                return $product->getValidated() && $product->getDeletedAt() == null;
                            });
        return count($validatedProducts) > 0;
    }

    /**
     * Update collected amount
     * @param $amount
     */
    public function addAmount($amount) {
        $this->collectedAmount += $amount;
    }

    /**
     * Calculate percentage of project funding progress
     * @return float
     */
    public function getProgressPercent() {
        return floor(($this->getCollectedAmount() / $this->getThreshold()) * 100);
    }


    /**
     * Calculate number of remaining days for project funding
     * @return integer
     */
    public function getRemainingDays()
    {
        return $this->getDateEnd()->diff(new \DateTime())->format('%a');
    }

    /**
     * Calculate number of remaining hours for project funding
     * @return integer
     */
    public function getRemainingHours()
    {
        $diff = $this->getDateEnd()->diff(new \DateTime());
        return $diff->h + ($diff->days*24);
    }

    /**
     * Calculate number of remaining minutes for project funding
     * @return integer
     */
    public function getRemainingMinutes()
    {
        $diff = $this->getDateEnd()->diff(new \DateTime());
        return ($diff->days * 24 * 60) + ($diff->h * 60) + $diff->i;
    }

    /**
     * Return the correct remaining time format to display
     * @return string
     */
    public function getRemainingTime()
    {
        $time = '';
        if($this->getRemainingDays() > 0) {
            $time .= $this->getRemainingDays() . ' jour(s) restant(s)';
        } else {
            if($this->getRemainingHours() > 0) {
                $time .= $this->getRemainingHours() . ' heure(s) restante(s)';
            } else {
                $time .= $this->getRemainingMinutes() . ' minute(s) restante(s)';
            }
        }
        return $time;
    }


    /**
     * Check if project date end is passed
     * @return bool
     */
    public function isPassed() {
        return $this->dateEnd < new \DateTime();
    }

    /**
     * Check if project is pending
     * @return bool
     */
    public function isPending() {
        return !$this->successful && !$this->failed && !$this->refunded && $this->isPassed();
    }

    /**
     * Check if project is still ongoing
     * @return bool
     */
    public function isOngoing() {
        return !$this->successful && !$this->failed && !$this->refunded && !$this->isPassed();
    }

    /**
     * Check if project is closed
     * @return bool
     */
    public function isClosed() {
        return $this->isPassed() && ($this->successful || ($this->failed && $this->refunded));
    }

    /**
     * Check if project is an event
     * @return bool
     */
    public function isEvent() {
        return $this->dateEvent != null;
    }

    /**
     * Check if project is way passed to send transactional message
     * @return bool
     */
    public function isWayPassed() {
        $date = new \DateTime();
        if ($this->isEvent()) {
            return $date > $this->dateEvent && $this->dateEvent->diff($date)->days > self::DAYS_BEFORE_WAY_PASSED_EVENT;
        }
        return $date > $this->dateEnd && $this->dateEnd->diff($date)->days > self::DAYS_BEFORE_WAY_PASSED;
    }


    /**
     * Count number of donations
     * @return integer
     */
    public function getNbDonations() {
        return count($this->getDonationsPaid());
    }

    /**
     * Count number of sales
     * @return integer
     */
    public function getNbSales() {
        return count($this->getSalesPaid());
    }

    /**
     * Count contributors; once a contributor who has paid several times
     * @return integer
     */
    public function getNbContributors() {
        $nbContributors = array_unique(array_map(function(XOrder $person) {
            return $person->getEmail();
        }, $this->getContributors()));
        return count($nbContributors);
    }


    /**
     * Get donations paid
     * @return array
     */
    public function getDonationsPaid() {
        return array_filter($this->contributions->toArray(), function(XContractFan $contribution) {
                    return $contribution->getIsDonation() && $contribution->getPaid() && ($this->failed || !$contribution->getRefunded());
               });
    }

    /**
     * Get donators
     * @param $beforeValidation
     * @return array
     */
    public function getDonators($beforeValidation = false) {
        if ($beforeValidation) {
            $donations = array_filter($this->getDonationsPaid(), function(XContractFan $cf) {
                return $this->dateValidation != null && $cf->getPayment()->getDate() <= $this->dateValidation;
            });
        } else {
            $donations = $this->getDonationsPaid();
        }

        if($donations == null || empty($donations)) {
            return [];
        }

        return array_map(function(XContractFan $cf) {
            return $cf->getPhysicalPerson();
        }, $donations);
    }


    /**
     * Get sales paid for some products
     * @param $products
     * @return array
     */
    public function getProductSalesPaid($products) {
        $productSalesPaid = [];
        foreach ($this->contributions as $contribution) {
            if(!empty($contribution->getPurchasesForProduct($products))) {
                $productSalesPaid[] = $contribution;
            }
        }
        return $productSalesPaid;
    }

    /**
     * Get sales paid
     * @return array
     */
    public function getSalesPaid() {
        return array_filter($this->contributions->toArray(), function(XContractFan $contribution) {
                    return !$contribution->getIsDonation() && $contribution->getPaid() && ($this->failed || !$contribution->getRefunded());
               });
    }

    /**
     * Get buyers
     * @param $beforeValidation, $products
     * @return array
     */
    public function getBuyers($beforeValidation = false, $products = null) {
        if ($beforeValidation) {
            if ($products != null) {
                $sales = array_filter($this->getProductSalesPaid($products), function(XContractFan $cf) {
                    return $this->dateValidation != null && $cf->getPayment()->getDate() <= $this->dateValidation;
                });
            } else {
                $sales = array_filter($this->getSalesPaid(), function(XContractFan $cf) {
                    return $this->dateValidation != null && $cf->getPayment()->getDate() <= $this->dateValidation;
                });
            }
        } else {
            if ($products != null) {
                $sales = $this->getProductSalesPaid($products);
            } else {
                $sales = $this->getSalesPaid();
            }
        }
        
        if($sales == null || empty($sales)) {
            return [];
        }

        return array_map(function(XContractFan $cf) {
            return $cf->getPhysicalPerson();
        }, $sales);

    }


    /**
     * Get all contributions paid
     * @return array
     */
    public function getContributionsPaid() {
        return array_filter($this->contributions->toArray(), function(XContractFan $contribution) {
                    return $contribution->getPaid() && ($this->failed || !$contribution->getRefunded());
               });
    }

    /**
     * Get all contributors
     * @param $beforeValidation, $products
     * @return array
     */
    public function getContributors($beforeValidation = false, $products = null) {
        return array_merge($this->getDonators($beforeValidation), $this->getBuyers($beforeValidation, $products));
    }


    /**

src/XBundle/Resources/views/XPublic/all_projects.html.twig
{% extends "XBundle::base.html.twig" %}

{% block body %}

<section class="container py-5">

    <h3 style="text-align: center">TOUS LES PROJETS</h3><br>
    {#<link rel = "stylesheet" href = "{{ asset('x/css/index.css') }}">#}

    <div id="projects">
        <!-- Filtre
        <div class="jplist-panel">
            <div class="jplist-ios-button">
                <i class="fa fa-sort"></i>jPList Actions
            </div>
            
            <select 
                class="jplist-select" 
                data-control-type="sort-select" 
                data-control-name="sort" 
                data-control-action="sort">
                
                <option data-path="default">Sort by</option>
                <option data-path=".card-title" data-order="asc" data-type="text">Title A-Z</option>
                <option data-path=".card-title" data-order="desc" data-type="text">Title Z-A</option>
                <option data-path=".card-funds" data-order="asc" data-type="number">Funds asc</option>
                <option data-path=".card-funds" data-order="desc" data-type="number">Funds desc</option>
                <option data-path=".date" data-order="asc" data-type="datetime">Date asc</option>
                <option data-path=".date" data-order="desc" data-type="datetime">Date desc</option>                
            </select>   

            <div class="text-filter-box">
                <i class="fa fa-search jplist-icon"></i>
                <input 
                    data-path=".card-title"
                    type="text"
                    value=""
                    placeholder="Filter by Title"
                    data-control-type="textbox"
                    data-control-name="title-filter"
                    data-control-action="filter"
                    />
            </div>

            <div class="text-filter-box">
                <i class="fa fa-search jplist-icon"></i>
                <input 
                    data-path=".badge"
                    type="text"
                    value=""
                    placeholder="Filter by Tag"
                    data-control-type="textbox"
                    data-control-name="tag-filter"
                    data-control-action="filter"
                    />
            </div>
        </div>
        -->

        <div class="container-fluid jp-list">
            <div class="row jp-list-item">
            {% for project in projects %}
                {% if not project.failed %}
                <div class="col-sm-4">
                    <a href="{{ path('x_project', {'id':project.id}) }}" class="custom-card">
                    <div class="card jp-list-item">
                            <img class="card-img-top" src="{{ asset(project.coverpic.webPath(project.coverpic)) }}" width="140" height="140"/>
                        <div class="card-body">
                            <h4 class="card-title">{{ project.title }}</h4>
                            <span class = "badge badge-warning">{{project.tag.name}}</span><br>
                            {% if project.hasThreshold %}
                                <strong>{{ project.collectedAmount }}€</strong> sur {{ project.threshold }}€
                            {% else %}
                                <strong>{{ project.collectedAmount }}€</strong> récolté(s)
                            {% endif %}
                            -
                            {% if project.remainingDays > 0 %}
                                <strong>{{ project.remainingDays }}</strong> jour(s) restant(s)
                            {% else %}
                                {% if project.remainingHours > 0 %}
                                    <strong>{{ project.remainingHours }}</strong> heure(s) restante(s)
                                {% else %}
                                    <strong>{{ project.remainingMinutes }}</strong> minute(s) restante(s)
                                {% endif %}
                            {% endif %}

                            {% if project.hasThreshold %}
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: {{ project.progressPercent }}%;" aria-valuenow="{{ project.progressPercent }}" aria-valuemin="0" aria-valuemax="100"><div class="card-funds" >{{ project.progressPercent}}%</div></div>
                                </div>
                            {% endif %}
                            
                            <div id = "bt{{loop.index}}">
                                {#<a href="{{ path('x_project', {'id' : project.id}) }}" class="btn btn-primary">Soutenez-le</a>#}
                                <!--Bouton pour compter les points-->
                                <button type="button" id = "{{loop.index}}" style = "float:right; background-color: #ff3333; border-color: #ff3333; width: 45px; height: 45px;text-align: center; padding: 6px 0; margin-top: 10px; font-size: 20px; line-height: 1.428571429; border-radius: 22.5px;"class="btn btn-primary btn-circle points-given" {%if not app.user %}data-toggle="modal" data-target="#login-modal" {% endif %}><span class="fa fa-caret-up"></span> <span id = "points">{{ project.points }}</span></a>
                                    <input type = "hidden" value = "{{ project.id }}" id = "id"/>
                                </button>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
                {% endif %}
                {#% if loop.index is divisible by(3) %}
                    </div>
                    <div class = "row jp-list-item" style = "margin-top : 3em" >
                {% else %}
                    <p> Pas (encore!) de projets </p>
                {% endif %#}
            {% else %}
                <p> Pas (encore!) de projets lancés</p>
            {% endfor %}
        </div>

    </div>

</section>
    
{% endblock %}

{% block additional_javascripts %}
    <script>
		$('document').ready(function(){	
				
			$('#projects').jplist({				
				itemsBox: '.list' 
				,itemPath: '.list-item' 
				,panelPath: '.jplist-panel'	
			});
		});
	</script>
{% endblock %}

src/XBundle/Resources/views/XPublic/catalog_projects.html.twig
{% extends "@X/base_catalog.html.twig" %}

{% block body %}

    <section class="container py-5" id="projects-catalog">

        <h3 class="text-center">TOUS LES PROJETS</h3>

        {% if projects_ongoing is empty and projects_successful is empty %}
            <p class="text-center">Pas (encore!) de projets lancés</p>
        {% else %}

            <!-- Filtre -->
            <div class="py-2 my-5">
                <!-- ios button: show/hide panel -->
                <div class="jplist-ios-button">
                    <i class="fa fa-sort"></i>
                    Filtrer...
                </div>

                <!-- panel -->
                <div class="jplist-panel box panel-top">
                    <!-- sort by category -->
                    <div class="jplist-drop-down" data-path=".project-category" data-control-type="filter-drop-down" data-control-action="filter" data-control-name="project-category-filter">
                        <div class="jplist-dd-panel"></div>
                        <ul>
                            <li class="active"><span data-path="default" style="color:grey">Catérogie</span></li>
                            {% for category in categories %}
                                {% set slug = "jplist-" ~ category.name|slug %}
                                <li>
                                    <span data-path=".{{ slug }}">{{ category.name }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <!-- search by title, artistname or tags -->
                    <div class="text-filter-box">
                        <i class="fa fa-search jplist-icon"></i>
                        <input data-path=".search-filter" type="text" value="" placeholder="Chercher..." data-control-type="textbox" data-control-name="model-text-filter" data-control-action="filter"/>
                    </div>

                    <!-- display ongoing projects -->
                    <div class="jplist-group" data-control-type="checkbox-group-filter" data-control-action="filter" data-control-name="project-ongoing" data-path=".project-ongoing">
                        <label class="custom-control custom-checkbox pl-4" for="checkbox-ongoing">
                            <input data-path=".project-ongoing" id="checkbox-ongoing" class="form-check-input custom-control-input" type="checkbox"{% if ongoing_checked %} checked{% endif %}>
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description">En cours</span>
                        </label>
                    </div>

                    <!-- display successful projects -->
                    <div class="jplist-group" data-control-type="checkbox-group-filter" data-control-action="filter" data-control-name="project-successful" data-path=".project-successful">
                        <label class="custom-control custom-checkbox pl-4" for="checkbox-successful">
                            <input data-path=".project-successful" id="checkbox-successful" class="form-check-input custom-control-input" type="checkbox"{% if successful_checked %} checked{% endif %}>
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description">Réussite</span>
                        </label>
                    </div>
                </div>
            </div>

            <div class="row jp-list">
                {% for project in projects_ongoing %}
                    {% include 'XBundle:XPublic/Card:card_project.html.twig' with {'bgwhite': true, 'jplist': true} %}
                {% endfor %}
                {% for project in projects_successful %}
                    {% include 'XBundle:XPublic/Card:card_project.html.twig' with {'bgwhite': true, 'jplist': true} %}
                {% endfor %}
            </div>
            <!-- no results found -->
            <div class="row jplist-no-results px-3">
                <p>Pas de résultat trouvé</p>
            </div>
        {% endif %}

    </section>
    
{% endblock %}

{% block additional_javascripts %}
    <script>
		$('document').ready(function(){	
			$('#projects-catalog').jplist({
				itemsBox: '.jp-list'
				,itemPath: '.jp-list-item'
				,panelPath: '.jplist-panel'
                ,noResults: '.jplist-no-results'
            });
		});
	</script
{% endblock %}

src/XBundle/Resources/views/XPublic/home.html.twig
{% extends "@X/base.html.twig" %}

{% block main_attributes %}class="home-main"{% endblock %}

{% block nav_details_links %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{{ path('x_homepage') ~ "#about" }}">À propos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{{ path('x_homepage') ~ "#contact" }}">Contact</a>
    </li>
{% endblock %}

{% block body %}

    <!-- About Section -->
    <section id="about">
        <div class="container p-5">
            <h3 class="text-center">CHAPOTS</h3>
        </div>
    </section>


    <!-- Projects Section -->
    <section class="container py-5">
        <h3 class="text-center">LES PROJETS EN COURS</h3><br>
        {% if projects is empty %}
            <p class="text-center">Pas (encore!) de projets lancés</p>
        {% else %}
            <div class="row jp-list">
                {% for project in projects %}
                    {% if loop.index < 4 %}
                        {% include 'XBundle:XPublic/Card:card_project.html.twig' with {'bgwhite': true, 'jplist': true} %}
                    {% endif %}
                {% endfor %}
            </div>
            <p class="text-center mt-3">
                <a class="btn btn-primary" href="{{ path('x_projects') }}">Voir tous les projets</a>
            </p>
        {% endif %}
    </section>


    <!-- Contact Section -->
    <section id="contact">
        <h3 class="text-center">CONTACT</h3><br>

        <div class="contact-section">
            {{ hidden_loader(true, false) }}
            <div class="container" id="contact-form-container">
                {% form_theme form ':Form:bootstrap_4_layout.html.twig' %}
                {{ form_start(form) }}
                    <div class="row">
                        <div class="col-12 col-md-6 form-line">
                            <div class="form-group">
                                {{ form_row(form.name) }}
                            </div>
                            <div class="form-group">
                                {{ form_row(form.email) }}
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-group">
                                {{ form_row(form.message) }}
                            </div>
                            <div>
                                <button type="submit"  name="g-recaptcha-response"
                                        class="g-recaptcha btn btn-default submit"
                                        data-sitekey="6LfklYEUAAAAAMj_B1O7c8RvimKn5GFunxRPyiBz" data-callback="onrecaptcha"><i class="fa fa-paper-plane" aria-hidden="true"></i> Envoyer</button>
                            </div>
                        </div>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </section>

{% endblock %}

{% block additional_javascripts %}
    {{ parent() }}
    <script async defer>
        $('button.submit').click(function() {
            var $name = "{{ form.vars.value.name }}";
            console.log("nom: " + $name);
            $('#contact-form-container').hide();
            $('.loader').show();
        });
        function onrecaptcha() {
            $('form').submit();
        }
    </script>
    <script src='https://www.google.com/recaptcha/api.js' async defer></script>

{% endblock %}

src/XBundle/Resources/views/XPublic/index.html.twig
{% extends "XBundle::base.html.twig" %}

{% block body %}
    <section class="container py-5">
        <h3 style="text-align: center">CHAPOTS</h3>
    </section>
    <hr>
    <section class="container py-5">
        <h3 style="text-align: center">LES PROJETS POPULAIRES</h3><br>
        <div class="container-fluid jp-list">
            <div class="row jp-list-item">
            {% for project in projects %}
                {% if not project.failed %}
                    <div class="col-sm-4">
                        <a href="{{ path('x_project', {'id':project.id}) }}" class="custom-card">
                        <div class="card jp-list-item">
                                <img class="card-img-top" src="{{ asset(project.coverpic.webPath(project.coverpic)) }}" width="140" height="140"/>
                            <div class="card-body">
                                <h4 class="card-title">{{ project.title }}</h4>
                                <span class = "badge badge-warning">{{project.tag.name}}</span><br>
                                {% if project.hasThreshold %}
                                    <strong>{{ project.collectedAmount }}€</strong> sur {{ project.threshold }}€
                                {% else %}
                                    <strong>{{ project.collectedAmount }}€</strong> récolté(s)
                                {% endif %}
                                -
                                {% if project.remainingDays > 0 %}
                                    <strong>{{ project.remainingDays }}</strong> jour(s) restant(s)
                                {% else %}
                                    {% if project.remainingHours > 0 %}
                                        <strong>{{ project.remainingHours }}</strong> heure(s) restante(s)
                                    {% else %}
                                        <strong>{{ project.remainingMinutes }}</strong> minute(s) restante(s)
                                    {% endif %}
                                {% endif %}

                                {% if project.hasThreshold %}
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: {{ project.progressPercent }}%;" aria-valuenow="{{ project.progressPercent }}" aria-valuemin="0" aria-valuemax="100"><div class="card-funds" >{{ project.progressPercent}}%</div></div>
                                </div>
                                {% endif %}

                                <div id = "bt{{loop.index}}">
                                    {#<a href="{{ path('x_project', {'id' : project.id}) }}" class="btn btn-primary">Soutenez-le</a>#}
                                    <!--Bouton pour compter les points-->
                                    <button type="button" id = "{{loop.index}}" style = "float:right; background-color: #ff3333; border-color: #ff3333; width: 45px; height: 45px;text-align: center; padding: 6px 0; margin-top: 10px; font-size: 20px; line-height: 1.428571429; border-radius: 22.5px;"class="btn btn-primary btn-circle points-given" {%if not app.user %}data-toggle="modal" data-target="#login-modal" {% endif %}><span class="fa fa-caret-up"></span> <span id = "points">{{ project.points }}</span></a>
                                        <input type = "hidden" value = "{{ project.id }}" id = "id"/>
                                    </button>
                                </div>
                            </div>
                        </div>
                        </a>
                    </div>
                {% endif %}
            {% else %}
                <p> Pas (encore!) de projets lancés</p>
            {% endfor %}
            </div>
        </div>
    </section>

    <hr>

    <section class="container py-5">
        <h3 style="text-align: center">CONTACT</h3><br>
        {#<div class="well">
            {{ form(form) }}
        </div>#}
    </section>

{% endblock %}

src/XBundle/Resources/views/XPublic/login.html.twig
{% extends "XBundle::base.html.twig" %}

{% trans_default_domain 'FOSUserBundle' %}

{% block body %}
    <div class="container py-5">
        <div class="x-login-content">
            {% if error is defined and error %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
            {% endif %}

            <div class="x-login-body">
                <div class="container">
                    <!-- design of the x-login header -->
                    <div class="login-header">
                        <!-- titre de la section -->
                        <h3 class="text-center">CONNEXION</h3><br>
                    </div>
                    <form action="{{ path('fos_user_security_check_x') }}" method="post">
                        <div class="form-group">
                            <input type="email" class="form-control" id="username" name="_um_username" {% if last_username is defined %}value="{{ last_username }}"{% endif %} placeholder="{{ 'security.login.username'|trans }}" required="required">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="password" name="_um_password" placeholder="{{ 'security.login.password'|trans }}" required="required">
                        </div>
                        <div class="form-group">
                            <label class="custom-control custom-checkbox pr-3" for="remember_me">
                                <input type="checkbox" id="remember_me" name="_remember_me" value="on" class="form-check-input custom-control-input" />
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">{{ 'security.login.remember_me'|trans }}</span>
                            </label>
                        </div>

                        <div class="text-center">
                            <button class="btn btn-primary text-uppercase position-relative um-login-button text-center" type="submit" id="_submit_um_connection" name="_submit"><!--
                                -->Connexion<!--
                            --></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/XBundle/Resources/views/XPublic/terms.html.twig
{% extends "@X/base.html.twig" %}

{% block body %}

    <div class="container py-5">
        <p>
            Conditions d'utilisations de Chapots
        </p>
    </div>

{% endblock %}