src/AppBundle/Entity/Notification.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Notification
 *
 * @ORM\Table(name="app_notification")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\NotificationRepository")
 */
class Notification
{
    public function __construct()
    {
        $this->date = new \DateTime();
        $this->seen = false;
    }

    public function isUnseen() {
        return !$this->seen;
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string", length=255)
     */
    private $type;

    /**
     * @var array
     *
     * @ORM\Column(name="params", type="array")
     */
    private $params;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

    /**
     * @var bool
     *
     * @ORM\Column(name="seen", type="boolean")
     */
    private $seen;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="notifications")
     */
    private $user;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     *
     * @return Notification
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set params
     *
     * @param array $params
     *
     * @return Notification
     */
    public function setParams($params)
    {
        $this->params = $params;

        return $this;
    }

    /**
     * Get params
     *
     * @return array
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Notification
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set seen
     *
     * @param boolean $seen
     *
     * @return Notification
     */
    public function setSeen($seen)
    {
        $this->seen = $seen;

        return $this;
    }

    /**
     * Get seen
     *
     * @return bool
     */
    public function getSeen()
    {
        return $this->seen;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     *
     * @return Notification
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }
}

src/AppBundle/Resources/views/Notifications/utils/complete.html.twig
<div class="notification">
    <h3>{{ title|raw }}</h3>
    <div>{{ content|raw }}</div>
</div>

src/AppBundle/Resources/views/Notifications/utils/menu_preview.html.twig
<a class="notification-trigger notification-menu-preview-content{% if notification.unseen %} unseen{% endif %}" href="{{ path('user_notification', {'id': notification.id}) }}">
    <div class="notification-menu-preview-item">
        <h6 class="notification-menu-preview-title">{{ title|raw }}</h6>
        <div class="notification-menu-preview-preview">{{ preview(content, 50)|raw }}</div>
    </div>
</a>

src/AppBundle/Resources/views/Notifications/utils/preview.html.twig
<tr class="notification-preview {% if notification.unseen %} table-warning{% endif %}">
    <td><a><b>{{ title }}</b></a>{% if notification.unseen %} - non lu {% endif %}</td>
    <td><div>{{ preview(content, 100)|raw }}</div></td>
    <td><a class="btn btn-primary notification-trigger" href="{{ path('user_notification', {'id': notification.id}) }}">Voir</a></td>
</tr>